### ISSUE TITLE
javadoc Markdown issues

### ISSUE THREAD

**Issue by nlisker** [eclipse-jdt/eclipse.jdt.ui#1800]
Trying to use Markdown documentation, I came across quite a few issues with it. I'm not sure if this feature is still WIP from Eclipse's perspective (it was delivered in Java 23) and which of these is known, so here is a summary from which individual issues can be created:

- [x] #2051 Javadoc view doesn't switch to MD docs when the cursor is placed in the docs area, unlike with HTML comments. The only way to switch to it is to click on the class name itself (for class docs).
- [x] #2051 Javadoc view doesn't update in real time as text is being typed for MD, but does for HTML.
- [x] #2500 Pressing enter while writing docs in MD places the caret (and the rest of the line) on the next line right after `///` instead of 1 space after that, as it does with HTML's `* `.
- [x] #2527 Typing `{@link Object#` pops up the suggestions, but in MD `[Object#` does not. Pressing ctrl+space will bring up the suggestions, so there is recognition of the context (it just needs some encouragement).
- [x] #2528, as if I'm typing a `char` in Java. This means that if I try to type `it's` it comes out as `it's'`.
- [x] #2529 Perhaps this is an enhancement request.
- [ ] Not sure if this is relevant for Eclipse, but syntax highlighting `(```java or ```css)` doesn't do anything. The JEP mentions external libraries being needed, but I wasn't sure if at least Java is automatically included. Perhaps it is a reasonable enhancement request to include java syntax coloring for JDT?
- [x] I hit #1615 as well. My compliance level for the project is 23 (with and without preview features enabled).
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3761 Using `[i]` inside a code block renders it as a broken link instead of literally:
  ```
  /// ```
  /// int i = 3;
  /// int[] d = new int[i];
  /// ```
  ```
  produces
  ```
  int i = 3;
  int[] d = new int<code><a href='eclipse-javadoc:%E2%98%82=bugs/src%3Cmarkdown%7BMDTest.java%E2%98%83MDTest%E2%98%82i'>i</a></code>;
  ```
- [x] Formatting (ctrl+shift+F) does not do anything in MD, while in HTML it wraps a long line according to the formatter setting.
- [x] https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/3000
- [x] https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/3092
- [x] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/5220
- [x] https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/3101

Tested with build id: I20241117-0600

**Comment by stephan-herrmann** [comment]
Thanks for the detailed report. Unfortunately I found it only now.

> I'm not sure if this feature is still WIP from Eclipse's perspective.

@jarthana  and I have worked on this from the jdt.core perspective (parser and DOM) and I added the essential rendering (via HTML) in jdt.ui.

Several of the features you reported as missing / broken I wasn't even aware of :)

I've added the "help wanted" label, as apparently nobody owns this feature (the interactive aspects of it) yet.

Only the last item regarding `[i]` in a fenced region sounds like something we can/should fix in jdt.core.

**Comment by stephan-herrmann** [comment]
> Only the last item regarding `[i]` in a fenced region sounds like something we can/should fix in jdt.core.

Fixed by https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3761, I have a jdt.ui test to be pushed after the next integration build (Y).

**Comment by stephan-herrmann** [comment]
> > Only the last item regarding `[i]` in a fenced region sounds like something we can/should fix in jdt.core.
> 
> Fixed by [eclipse-jdt/eclipse.jdt.core#3761](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3761), I have a jdt.ui test to be pushed after the next integration build (Y).

Test added via #2052

**Comment by nlisker** [comment]
> > * Javadoc view doesn't switch to MD docs when the cursor is placed in the docs area, unlike with HTML comments. The only way to switch to it is to click on the class name itself (for class docs).
> > * Javadoc view doesn't update in real time as text is being typed for MD, but does for HTML.
> 
> Both these issues are addressed by PR [#2051](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2051)

Just tested these. They still existed on I20250314-1800 but fixed by I20250326-1800.

**Comment by stephan-herrmann** [comment]
Another related feature request: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2037

**Comment by nlisker** [comment]
Should I submit a single issue for each unfixed item on the list? I'd assume most of them should be easy to fix considering the behavior exists in standard javadoc.

**Comment by andy-goryachev** [comment]
I just upgraded to 
```
Version: 2026-06 (4.40.0)
Build id: 20260604-0653
```
on Windows and I don't see markdown javadoc rendered in the Preview window.
Has the feature been released?

**Comment by stephan-herrmann** [comment]
> I just upgraded to
> 
> ```
> Version: 2026-06 (4.40.0)
> Build id: 20260604-0653
> ```
> 
> on Windows and I don't see markdown javadoc rendered in the Preview window. Has the feature been released?

The feature has been released as part of JDT's support for Java 23, see https://www.eclipse.org/lists/eclipse-dev/msg12316.html

It is available in standard builds since 2024-09-18.

This is the new&noteworthy entry for the feature with screenshots: https://eclipse.dev/eclipse/news/news.html?file=4.34/jdt.html#markdown-doc

**Comment by andy-goryachev** [comment]
Thank you @stephan-herrmann for a quick response.  However, in my case it does not work:

<img width="658" height="504" alt="Image" src="https://github.com/user-attachments/assets/d6b3b1b1-0a33-4d69-9850-839831d8621e" />

Is there a setting / config option that needs to be toggled, perhaps in one of the .workspace files?

**Comment by stephan-herrmann** [comment]
> Thank you @stephan-herrmann for a quick response. However, in my case it does not work:
> Is there a setting / config option that needs to be toggled, perhaps in one of the .workspace files?

Easiest questions first:
* is that project configured for Java 23 or greater?
* do you see anything related in the error log?

**Comment by andy-goryachev** [comment]
Nothing related in the error log.
The project is configured for java 26.

**Comment by stephan-herrmann** [comment]
> Nothing related in the error log. The project is configured for java 26.

So it should work. 

Are you able to set up an environment for debugging Eclipse? If so, I could supply a few breakpoints where you could check what parts work / don't work.

Otherwise, the best I can advise is: create a small project that reproduces the problem and upload it including all its configuration files (`.project`, `.classpath`, `.settings/*`), so that we can take a look. When preparing the reproducer please try it in a minimal eclipse installation, ideally [Eclipse SDK](https://download.eclipse.org/eclipse/downloads/drops4/R-4.40-202606010713/#eclipse-sdk), with no further plugins installed.

Thanks.

**Comment by andy-goryachev** [comment]
I've created a new project and it shows markdown javadoc.  Something in the old workspace causes it not to show it - what could it be?  Is there a set of files I can safely delete from the .workspace directory?

(I've had this problem before - Eclipse does not upgrade workspace cleanly)

edit: this might be misleading - I am using the same workspace for both projects.

**Comment by andy-goryachev** [comment]
So it turns out `$PROJECT/.settings` must contain the **org.eclipse.jdt.core.prefs** file:
```
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.codegen.targetPlatform=26
org.eclipse.jdt.core.compiler.codegen.unusedLocal=preserve
org.eclipse.jdt.core.compiler.compliance=26
org.eclipse.jdt.core.compiler.debug.lineNumber=generate
org.eclipse.jdt.core.compiler.debug.localVariable=generate
org.eclipse.jdt.core.compiler.debug.sourceFile=generate
org.eclipse.jdt.core.compiler.problem.assertIdentifier=error
org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=disabled
org.eclipse.jdt.core.compiler.problem.enumIdentifier=error
org.eclipse.jdt.core.compiler.problem.reportPreviewFeatures=warning
org.eclipse.jdt.core.compiler.release=enabled
org.eclipse.jdt.core.compiler.source=26
```

Apparently, the workspace settings are not sufficient.

**Comment by stephan-herrmann** [comment]
> Apparently, the workspace settings are not sufficient.

If the projects omits specifying source / compliance versions, then the workspace settings are correctly applied and markdown hover is correctly rendered for me.

I guess your projects settings simply overrode the workspace settings, in which case the observed behavior is to be expected.

**Comment by andy-goryachev** [comment]
What settings?  Are there specific settings that control javadoc view behavior?

Here is what I have/had in the workspace settings:

<img width="1166" height="845" alt="Image" src="https://github.com/user-attachments/assets/7ac628e5-a1c6-4b10-a2b5-bbbb18bb7348" />

**Comment by stephan-herrmann** [comment]
Please just properly configure your project as you had shown before. Markdown javadoc is supported only since Java 23, so if your project specifies a lower version, the compiler will not be able to parse any markdown comments, and hence nothing can be rendered. The workspace preferences take effect only for those options that a project omits to specify.

If you still have problems please file a new issue, as we are already drowning the original purpose of this issue by lengthy discussion.

**Comment by andy-goryachev** [comment]
ok, sorry.

**Comment by stephan-herrmann** [comment]
@nlisker  it seems your list has gradually / silently been resolved 😄. So should we call it success and close this issue?

I think that adding formatting for markdown is a sizable project of its own, which is not required for closing this issue, OK?

**Comment by nlisker** [comment]
> [@nlisker](https://github.com/nlisker) it seems your list has gradually / silently been resolved 😄. So should we call it success and close this issue?

The issue is somewhat of a live list - more issues were added over time, Recently, @jjohnstn caught up with them, so I think we can call it completed.
 
> I think that adding formatting for markdown is a sizable project of its own, which is not required for closing this issue, OK?

You mean syntax highlighting? Formatting works.

**Comment by stephan-herrmann** [comment]
> > I think that adding formatting for markdown is a sizable project of its own, which is not required for closing this issue, OK?
> 
> You mean syntax highlighting? Formatting works.

I meant https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4244 and hadn't checked why it is still open 😎

**Comment by nlisker** [comment]
I forgot that issue exists :D
